/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/

--find the total number of customers by countries
SELECT country, COUNT(customer_key) AS total_no_customers 
FROM gold.dim_customers
GROUP BY country
ORDER BY total_no_customers DESC;

--find the total number of customers by gender
SELECT gender, COUNT(customer_key) AS total_no_customers 
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_no_customers DESC;

--Find total product by each category
SELECT category, COUNT(product_key) AS total_no_products 
FROM gold.dim_products
GROUP BY category
ORDER BY total_no_products DESC;

-- What is the average costs in each category?
SELECT category, AVG(cost) AS average_cost
FROM gold.dim_products
GROUP BY category
ORDER BY average_cost DESC;

 --What is the total revenue generated for each category?
SELECT  dm.category, SUM(fs.sales_amount) AS total_revenue 
FROM gold.fact_sales fs
LEFT JOIN gold.dim_products dm
ON fs.product_key = dm.product_key
GROUP BY dm.category
ORDER BY total_revenue DESC;
 

 --What is the total revenue generated by each customer?
SELECT  dc.customer_key,dc.first_name, dc.last_name, SUM(fs.sales_amount) AS total_revenue 
FROM gold.fact_sales fs
LEFT JOIN gold.dim_customers dc
ON fs.customer_key = dc.customer_key
GROUP BY dc.customer_key,dc.first_name,dc.last_name
ORDER BY total_revenue DESC;


--what is the distribution of items sold across countries?
SELECT dc.country, SUM(fs.quantity) AS total_distribution 
FROM gold.fact_sales fs
LEFT JOIN gold.dim_customers dc
ON fs.customer_key = dc.customer_key
GROUP BY dc.country
ORDER BY total_distribution DESC;
